services:
  server:
    build:
      context: .
      dockerfile: Server/dockerfile.server
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/app
      - /app/node_modules
    environment:
      PORT: ${PORT:-5000}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client/Biler-Market/dockerfile.client
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./client/Biler-Market:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
