# ─── Development Stage ───────────────────────────────────────────
FROM node:22-alpine AS dev

WORKDIR /app

COPY client/Biler-Market/package*.json ./

RUN npm install --legacy-peer-deps

COPY client/Biler-Market/ .

EXPOSE 5173

CMD ["npm", "run", "dev"]


# ─── Build Stage ─────────────────────────────────────────────────
FROM node:22-alpine AS build

WORKDIR /app

COPY client/Biler-Market/package*.json ./

RUN npm install --legacy-peer-deps

COPY client/Biler-Market/ .

RUN npm run build


# ─── Production Stage ────────────────────────────────────────────
FROM nginx:alpine AS prod

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]