# Devlopment Server Dockerfile

FROM node:22-alpine as dev

# Set the working directory
WORKDIR /app

# Copy the package files
COPY Server/package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the files
COPY Server/ .

#Run the server
CMD ["npx", "nodemon", "server.js"]

# Production Dockerfile
FROM node:22-alpine as prod

# Set the working directory
WORKDIR /app

# Copy the package files
COPY Server/package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the files
COPY Server/ .

#Run the server
CMD ["node", "server.js"]